language: python
dist: trusty
python:
- '3.6'
- nightly
install:
- pip install pipenv
- make install-dev
- make install-in-venv
script:
- make test
notifications:
  slack:
    secure: E1c1nT40W2Bc6cfpucMWyrWppFQ2rywp9/nf4UnLjjo6UE6PwFBxMDMuQF6nlRJK2NW0HanZmViHDX13oUP6B03REwmoPV4oBb+GD997F1LdCmz5WVgh1wQwIXM0Zuiwp7XGR0Zt8Rj7oGLpbPSIwwAMW+WkgAHWtfDIj5dHxQpPYoijKzZPVfzWA9aiVjgRNeWoqyJ9pJPTGEnW+q0wOfuCUZxAID2RYdId+1WEuujLlPgUiDW/qoNWeX+Dj5/A5sQJEgFT4DFOO+Rtn81emjse0umnCwxpdB2M0386nuOJQTBK1vKymzoJSF2qrWV0xKybeoz8OzrBPn+RaR7YdetO3WacLqJOo2fJ2qIexRyy/ygyvM3lEjIT4+2oa2wWO5phMHpnCMRhJ3bZ0nWyHIcE/CE2PFzqkmITKuS5ObZF2DQ33qbaHjqIshexa23cNz3W1j1vjE3ZwvBFqEX92iHALiTAOUps214m+8lR+DKMqJF+b4DEvgKz0EJO306mlizDW5D+QGDjBayEpkw+F1VNNPK4qC1H0m6bcaVMdklas+HxoDL9dv05zbB0IR+UDHEJgz46t4X9Yo0KdCU0ndT/eUb8Gdo/JO8ULUB8KTothW/g/dyS0eMMu3DJr4bCFLlz3IsEo7q3x3cv4o4X8c4V/GAGY2UNa+PJLZnvvaM=
